services:
  pretty-smart-editor:
    build:
      context: .
      dockerfile: dockerfile
    container_name: pretty-smart-editor-api-prod
    ports:
      - "18002:4000"
    restart: unless-stopped
    networks:
      - prettyclose
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY="placeholder"
    volumes:
      - ./src/uploads:/usr/src/app/dist/uploads

networks:
  prettyclose:
    external: true
    name: prettyclose
